### ISSUE TITLE
Flash it on "standard dokuwiki"

### ISSUE THREAD

**Issue by ghost** [andjar/dokuroam#3]
Hey, first of all thanks for the awesome work,
Is it possible to use the flashit plugin on a standard dokuwiki?

Thank you!

**Comment by andjar** [comment]
Hi! Thank you for showing interest and sorry for the late answer. It should indeed be possible. I think you only need these files:

* https://github.com/andjar/dokuroam/tree/master/lib/plugins/flashit - extract questions from the wiki and make database
  * Note that the path to the flashit files in the roam folder is hardcoded, so you need to change these references to the path on your own server
* https://github.com/andjar/dokuroam/blob/master/conf/userall.css - styling questions within the text
* https://github.com/andjar/dokuroam/tree/master/roam/flashit - the actual flash card files
  * I think you need to use an iframe poiting to index.php to have the flashcards inside the wiki

**Comment by ghost** [comment]
Thank you!!
